version: '3.9'

services:

  app:
    build: .
    container_name: sales-copilot
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY_AURORA}
      CLOSECRM_API_KEY: ${CLOSECRM_API_KEY}
      SCRAPINGBOT_USERNAME: ${SCRAPINGBOT_USERNAME}
      SCRAPINGBOT_API_KEY: ${SCRAPINGBOT_API_KEY}
      SCRAPINGDOG_API_KEY: ${SCRAPINGDOG_API_KEY}
    ports:
      - 8502:8501
    tty: true
